// Code generated by protoc-gen-go. DO NOT EDIT.
// source: robot/robot.proto

package robot

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Position struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_robot_021271b7dcc70e85, []int{0}
}
func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (dst *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(dst, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type MoveRequest struct {
	Robot                string    `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
	Origin               *Position `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Target               *Position `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_robot_021271b7dcc70e85, []int{1}
}
func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (dst *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(dst, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetRobot() string {
	if m != nil {
		return m.Robot
	}
	return ""
}

func (m *MoveRequest) GetOrigin() *Position {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *MoveRequest) GetTarget() *Position {
	if m != nil {
		return m.Target
	}
	return nil
}

type MoveResponse struct {
	Distance             float64  `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveResponse) Reset()         { *m = MoveResponse{} }
func (m *MoveResponse) String() string { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()    {}
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_robot_021271b7dcc70e85, []int{2}
}
func (m *MoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResponse.Unmarshal(m, b)
}
func (m *MoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResponse.Marshal(b, m, deterministic)
}
func (dst *MoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResponse.Merge(dst, src)
}
func (m *MoveResponse) XXX_Size() int {
	return xxx_messageInfo_MoveResponse.Size(m)
}
func (m *MoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResponse proto.InternalMessageInfo

func (m *MoveResponse) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func init() {
	proto.RegisterType((*Position)(nil), "robot.Position")
	proto.RegisterType((*MoveRequest)(nil), "robot.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "robot.MoveResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MovementServiceClient is the client API for MovementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MovementServiceClient interface {
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
}

type movementServiceClient struct {
	cc *grpc.ClientConn
}

func NewMovementServiceClient(cc *grpc.ClientConn) MovementServiceClient {
	return &movementServiceClient{cc}
}

func (c *movementServiceClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/robot.MovementService/Move", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovementServiceServer is the server API for MovementService service.
type MovementServiceServer interface {
	Move(context.Context, *MoveRequest) (*MoveResponse, error)
}

func RegisterMovementServiceServer(s *grpc.Server, srv MovementServiceServer) {
	s.RegisterService(&_MovementService_serviceDesc, srv)
}

func _MovementService_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovementServiceServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/robot.MovementService/Move",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovementServiceServer).Move(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MovementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "robot.MovementService",
	HandlerType: (*MovementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Move",
			Handler:    _MovementService_Move_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "robot/robot.proto",
}

func init() { proto.RegisterFile("robot/robot.proto", fileDescriptor_robot_021271b7dcc70e85) }

var fileDescriptor_robot_021271b7dcc70e85 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xca, 0x4f, 0xca,
	0x2f, 0xd1, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0x92, 0x1a,
	0x17, 0x47, 0x40, 0x7e, 0x71, 0x66, 0x49, 0x66, 0x7e, 0x9e, 0x10, 0x0f, 0x17, 0x63, 0x85, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x63, 0x10, 0x63, 0x05, 0x88, 0x57, 0x29, 0xc1, 0x04, 0xe1, 0x55, 0x2a,
	0x95, 0x72, 0x71, 0xfb, 0xe6, 0x97, 0xa5, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x89,
	0x70, 0x41, 0xf4, 0x83, 0x95, 0x73, 0x06, 0x41, 0x38, 0x42, 0xea, 0x5c, 0x6c, 0xf9, 0x45, 0x99,
	0xe9, 0x99, 0x79, 0x60, 0x7d, 0xdc, 0x46, 0xfc, 0x7a, 0x10, 0x1b, 0x61, 0x36, 0x04, 0x41, 0xa5,
	0x41, 0x0a, 0x4b, 0x12, 0x8b, 0xd2, 0x53, 0x4b, 0x24, 0x98, 0x71, 0x28, 0x84, 0x48, 0x2b, 0x69,
	0x71, 0xf1, 0x40, 0xac, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x92, 0xe2, 0xe2, 0x48, 0xc9,
	0x2c, 0x2e, 0x49, 0xcc, 0x4b, 0x4e, 0x85, 0xba, 0x14, 0xce, 0x37, 0x72, 0xe1, 0xe2, 0x07, 0xa9,
	0xcd, 0x4d, 0xcd, 0x2b, 0x09, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x32, 0xe4, 0x62, 0x01,
	0x09, 0x09, 0x09, 0x41, 0xcd, 0x47, 0xf2, 0x82, 0x94, 0x30, 0x8a, 0x18, 0xc4, 0x7c, 0x25, 0x86,
	0x24, 0x36, 0x70, 0xf0, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xe0, 0x52, 0x2c, 0x33,
	0x01, 0x00, 0x00,
}
